# Setup
title:        Good First Issues
tagline:      ""
baseurl:      "/good-first-issues"
github:       "https://github.com/hpc-social/good-first-issues"

# About/contact
author:
  name:       "@vsoch"
  url:        https://hpc-social/good-first-issues

# Collections
collections:
    issues:
      output: false
      permalink: /:collection/:title/

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

#Others
markdown: kramdown
